-- 기존 게시글은 유지하고, 자동 번호 설정이 없을 때만 시퀀스를 연결한다.
BEGIN;
CREATE TABLE IF NOT EXISTS posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL
);
LOCK TABLE posts IN ACCESS EXCLUSIVE MODE;
DO $$
DECLARE
    next_id BIGINT;
    previous_id BIGINT;
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'posts'
          AND column_name = 'id' AND is_identity = 'NO' AND column_default IS NULL
    ) THEN
        CREATE SEQUENCE IF NOT EXISTS posts_id_seq;
        ALTER SEQUENCE posts_id_seq OWNED BY posts.id;
        ALTER TABLE posts ALTER COLUMN id SET DEFAULT nextval('posts_id_seq'::regclass);
        SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM posts;
        SELECT COALESCE(last_value, 0) INTO previous_id FROM pg_sequences
        WHERE schemaname = current_schema() AND sequencename = 'posts_id_seq';
        PERFORM setval('posts_id_seq', GREATEST(next_id, COALESCE(previous_id, 0) + 1, 1), false);
    END IF;
END $$;
COMMIT;
